resty/urls.py
from django.conf.urls import patterns, include, url



urlpatterns = patterns('',
    url(r'^', include('stuff.urls')),
)

stuff/urls.py
from django.conf.urls import patterns, include, url
from rest_framework import routers, serializers, viewsets
from .models import *
from .views import *
from .rest import *


router = routers.DefaultRouter()
router.register(r'muffins', MuffinViewSet)
router.register(r'orders', OrderViewSet, base_name='order')


urlpatterns = patterns('',
    url(r'^$', OrderListView.as_view()),
    url(r'^', include(router.urls)),
)

stuff/models.py
from django.db import models


class Muffin(models.Model):
    name = models.CharField(max_length=255)
    size = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name


class Order(models.Model):
    muffin = models.ForeignKey(Muffin)
    amount = models.PositiveSmallIntegerField()
    urgency = models.PositiveSmallIntegerField(
        choices=((0, 'yes, please'), (1, 'meh'), (2, 'come on')),
        default=2
    )

stuff/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import *


class OrderListView(ListView):
    model = Order

    @property
    def query(self):
        return self.request.GET.get('query', '')

    def get_queryset(self):
        orders = super(OrderListView, self).get_queryset()
        try:
            orders = orders.filter(muffin__id=self.query)
        except ValueError:
            orders = orders.filter(muffin__name__icontains=self.query)
        return orders

    def get_context_data(self, **kwargs):
        context = super(OrderListView, self).get_context_data(**kwargs)
        context.update({
            'query': self.query
        })
        return context

resty/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Muffin world!</title>
    <link rel="stylesheet" href="https://bootswatch.com/superhero/bootstrap.min.css">
    <style>
        body { padding-bottom: 70px; }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  </head>
  <body>

    <div class="container">
        <div class="page-header">
            <h1>Muffin world!</h1>
            <p class="lead">
                Muffins are awesome!
            </p>
        </div>
        {% block content %}{% endblock %}
    </div>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  </body>
</html>

stuff/templates/stuff/order_list.html
{% extends 'base.html' %}

{% block content %}
    <form method="get">
        <div class="input-group">
            <input type="search" value="{{ query }}" name="query" class="form-control" placeholder="Filter orders with muffin name or muffin id...">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">Filter</button>
                <a href="/muffins/" type="button" class="btn btn-default">
                    <span class="glyphicon glyphicon-cog"></span>
                    API for Muffin
                </a>
                <a href="/orders/" type="button" class="btn btn-default">
                    <span class="glyphicon glyphicon-cog"></span>
                    API for Order
                </a>
            </span>
        </div>
    </form>
    <table class="table table-striped">
        <tr>
            <th>order id</th>
            <th>muffin id</th>
            <th>muffin name</th>
            <th>muffin size</th>
            <th>amount of muffins</th>
            <th>order urgency</th>
        </tr>
        {% for object in object_list %}
            <tr>
                <td>{{ object.pk }}</td>
                <td>{{ object.muffin.pk }}</td>
                <td>{{ object.muffin.name }}</td>
                <td>{{ object.muffin.size }}</td>
                <td>{{ object.amount }}</td>
                <td>{{ object.get_urgency_display }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}